In [27]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import joblib

In [28]:
model = joblib.load('model.pkl')

In [29]:
pred_data = pd.read_pickle('pred_data.pkl')

In [30]:
train_X = pd.read_pickle('train_X.pkl')

In [31]:
for col in train_X.columns:
    if col not in pred_data.columns:
        pred_data[col] = 0

In [32]:
X_cols = train_X.columns

In [33]:
pred_X = pred_data[X_cols]

In [34]:
pred_X = pred_X.fillna(pred_X.mean())

In [35]:
#pred_X = (pred_X - train_X.mean()) / train_X.std()

In [36]:
pred_X

    LapPosition_1  LapPosition_2  PrevPosition1  PrevPosition2  PrevPosition3
0              17              0            2.0            1.0           15.0
1              15             16           19.0            9.0           10.0
2               4              4            3.0           20.0            1.0
3               0              2            6.0            4.0            3.0
4              16              3            1.0            7.0            2.0
5               1             14            9.0            6.0            6.0
6               3             15           15.0           18.0           20.0
7               5              5           18.0           14.0           13.0
8              12             13           20.0           15.0           18.0
9              13             10            8.0           12.0           16.0
10              2              1           13.0            8.0           17.0
11             19              7           16.0           17.0           12.0
12              7             11           17.0           10.0           11.0
13             18             18           12.0           11.0            7.0
14             10             17            7.0           13.0           19.0
15             14             19            5.0            3.0            8.0
16             11             12            4.0            5.0            5.0
17              9              9           11.0            2.0            4.0
18              6              8           14.0           19.0           14.0
19              8              6           10.0           16.0            9.0

In [37]:
pred_Y = model.predict(pred_X)

In [39]:
results = pd.DataFrame(data = {'DriverNumber': pred_data['DriverNumber'], 'Pred': pred_Y}).sort_values('Pred')
results['PredPosition'] = range(1, len(results) + 1)

In [40]:
results

   DriverNumber       Pred  PredPosition
4            16   4.504761             1
3            14   4.910306             2
16           55   5.624142             3
0             1   5.783636             4
15           44   6.286057             5
17           63   6.555320             6
5            18   7.470009             7
2            11   8.443232             8
13           31  10.694752             9
9            22  11.303260            10
10           23  11.313892            11
19           81  11.337707            12
14            4  12.059631            13
12           27  12.297926            14
1            10  12.785136            15
7            20  13.984929            16
11           24  14.487013            17
18           77  14.550126            18
6             2  15.984945            19
8            21  16.417748            20

In [42]:
pred_data[list(X_cols) + ['DriverNumber', 'Team', 'Driver', 'EventName']].sort_values('LapPosition_1')

,LapPosition_1,LapPosition_2,PrevPosition1,PrevPosition2,PrevPosition3,DriverNumber,Team,Driver,EventName
3,0,2,6.0,4.0,3.0,14,Aston Martin,ALO,Miami Grand Prix
5,1,14,9.0,6.0,6.0,18,Aston Martin,STR,Miami Grand Prix
10,2,1,13.0,8.0,17.0,23,Williams,ALB,Miami Grand Prix
6,3,15,15.0,18.0,20.0,2,Williams,SAR,Miami Grand Prix
2,4,4,3.0,20.0,1.0,11,Red Bull Racing,PER,Miami Grand Prix
7,5,5,18.0,14.0,13.0,20,Haas F1 Team,MAG,Miami Grand Prix
18,6,8,14.0,19.0,14.0,77,Alfa Romeo,BOT,Miami Grand Prix
12,7,11,17.0,10.0,11.0,27,Haas F1 Team,HUL,Miami Grand Prix
19,8,6,10.0,16.0,9.0,81,McLaren,PIA,Miami Grand Prix
17,9,9,11.0,2.0,4.0,63,Mercedes,RUS,Miami Grand Prix
14,10,17,7.0,13.0,19.0,4,McLaren,NOR,Miami Grand Prix
16,11,12,4.0,5.0,5.0,55,Ferrari,SAI,Miami Grand Prix
8,12,13,20.0,15.0,18.0,21,AlphaTauri,DEV,Miami Grand Prix
9,13,10,8.0,12.0,16.0,22,AlphaTauri,TSU,Miami Grand Prix
15,14,19,5.0,3.0,8.0,44,Mercedes,HAM,Miami Grand Prix
1,15,16,19.0,9.0,10.0,10,Alpine,GAS,Miami Grand Prix
4,16,3,1.0,7.0,2.0,16,Ferrari,LEC,Miami Grand Prix
0,17,0,2.0,1.0,15.0,1,Red Bull Racing,VER,Miami Grand Prix
13,18,18,12.0,11.0,7.0,31,Alpine,OCO,Miami Grand Prix
11,19,7,16.0,17.0,12.0,24,Alfa Romeo,ZHO,Miami Grand Prix